name: cpp-linter

on:
  push:
    branches:
      - main
    paths-ignore: 
      - "docs/**"
      - "design_doc/**"
  pull_request:
    paths-ignore: 
      - "docs/**"
      - "design_doc/**"

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shenxianpeng/cpp-linter-action@master
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          files-changed-only: false
          file-annotations: false
